import {PropertyInterface, PropertyType} from "../d";

export const redProperties: [PropertyInterface, PropertyInterface, PropertyInterface] = [
    {
        name: "Kentucky Avenue",
        color: PropertyType.Red,
        price: 220,
        rentnohouse: 18,
        rent1house: 90,
        rent2house: 250,
        rent3house: 700,
        rent4house: 875,
        renthotel: 1050,
        mortgage: 110,
        housecost: 150,
        hotelcost: 150,
    },
    {
        name: "Indiana Avenue",
        color: PropertyType.Red,
        price: 220,
        rentnohouse: 18,
        rent1house: 90,
        rent2house: 250,
        rent3house: 700,
        rent4house: 875,
        renthotel: 1050,
        mortgage: 110,
        housecost: 150,
        hotelcost: 150,
    },
    {
        name: "Illinois Avenue",
        color: PropertyType.Red,
        price: 240,
        rentnohouse: 20,
        rent1house: 100,
        rent2house: 300,
        rent3house: 750,
        rent4house: 925,
        renthotel: 1100,
        mortgage: 120,
        housecost: 150,
        hotelcost: 150,
    },
];

export const yellowProperties: [PropertyInterface, PropertyInterface, PropertyInterface] = [
    {
        name: "Atlantic Avenue",
        color: PropertyType.Yellow,
        price: 260,
        rentnohouse: 22,
        rent1house: 110,
        rent2house: 330,
        rent3house: 800,
        rent4house: 975,
        renthotel: 1150,
        mortgage: 130,
        housecost: 150,
        hotelcost: 150,
    },
    {
        name: "Ventnor Avenue",
        color: PropertyType.Yellow,
        price: 260,
        rentnohouse: 22,
        rent1house: 110,
        rent2house: 330,
        rent3house: 800,
        rent4house: 975,
        renthotel: 1150,
        mortgage: 130,
        housecost: 150,
        hotelcost: 150,
    },
    {
        name: "Marvin Gardens",
        color: PropertyType.Yellow,
        price: 280,
        rentnohouse: 24,
        rent1house: 120,
        rent2house: 360,
        rent3house: 850,
        rent4house: 1025,
        renthotel: 1200,
        mortgage: 140,
        housecost: 150,
        hotelcost: 150,
    }
];

export const greenProperties: [PropertyInterface, PropertyInterface, PropertyInterface] = [
    {
        name: "Pacific Avenue",
        color: PropertyType.Green,
        price: 300,
        rentnohouse: 26,
        rent1house: 130,
        rent2house: 390,
        rent3house: 900,
        rent4house: 1100,
        renthotel: 1275,
        mortgage: 150,
        housecost: 200,
        hotelcost: 200,
    },
    {
        name: "North Carolina Avenue",
        color: PropertyType.Green,
        price: 300,
        rentnohouse: 26,
        rent1house: 130,
        rent2house: 390,
        rent3house: 900,
        rent4house: 1100,
        renthotel: 1275,
        mortgage: 150,
        housecost: 200,
        hotelcost: 200,
    },
    {
        name: "Pennsylvania Avenue",
        color: PropertyType.Green,
        price: 320,
        rentnohouse: 28,
        rent1house: 150,
        rent2house: 450,
        rent3house: 1000,
        rent4house: 1200,
        renthotel: 1400,
        mortgage: 160,
        housecost: 200,
        hotelcost: 200,
    }
];

export const darkBlueProperties: [PropertyInterface, PropertyInterface] = [
    {
        name: "Park Place",
        color: PropertyType.DarkBlue,
        price: 350,
        rentnohouse: 35,
        rent1house: 175,
        rent2house: 500,
        rent3house: 1100,
        rent4house: 1300,
        renthotel: 1500,
        mortgage: 175,
        housecost: 200,
        hotelcost: 200,
    },
    {
        name: "Boardwalk",
        color: PropertyType.DarkBlue,
        price: 400,
        rentnohouse: 50,
        rent1house: 200,
        rent2house: 600,
        rent3house: 1400,
        rent4house: 1700,
        renthotel: 2000,
        mortgage: 200,
        housecost: 200,
        hotelcost: 200,
    }
];

export const brownProperties: [PropertyInterface, PropertyInterface] = [
    {
        name: "Mediterranean Avenue",
        color: PropertyType.Brown,
        price: 60,
        rentnohouse: 2,
        rent1house: 10,
        rent2house: 30,
        rent3house: 90,
        rent4house: 160,
        renthotel: 250,
        mortgage: 30,
        housecost: 50,
        hotelcost: 50,
    },
    {
        name: "Baltic Avenue",
        color: PropertyType.Brown,
        price: 60,
        rentnohouse: 4,
        rent1house: 20,
        rent2house: 60,
        rent3house: 180,
        rent4house: 320,
        renthotel: 450,
        mortgage: 30,
        housecost: 50,
        hotelcost: 50,
    },
];

export const lightBlueProperties: [PropertyInterface, PropertyInterface, PropertyInterface] = [
    {
        name: "Oriental Avenue",
        color: PropertyType.LightBlue,
        price: 100,
        rentnohouse: 6,
        rent1house: 30,
        rent2house: 90,
        rent3house: 270,
        rent4house: 400,
        renthotel: 550,
        mortgage: 50,
        housecost: 50,
        hotelcost: 50,
    },
    {
        name: "Vermont Avenue",
        color: PropertyType.LightBlue,
        price: 100,
        rentnohouse: 6,
        rent1house: 30,
        rent2house: 90,
        rent3house: 270,
        rent4house: 400,
        renthotel: 550,
        mortgage: 50,
        housecost: 50,
        hotelcost: 50,
    },
    {
        name: "Connecticut Avenue",
        color: PropertyType.LightBlue,
        price: 120,
        rentnohouse: 8,
        rent1house: 40,
        rent2house: 100,
        rent3house: 300,
        rent4house: 450,
        renthotel: 600,
        mortgage: 60,
        housecost: 50,
        hotelcost: 50,
    },
];

export const pinkProperties: [PropertyInterface, PropertyInterface, PropertyInterface] = [
    {
        name: "St. Charles Place",
        color: PropertyType.Pink,
        price: 140,
        rentnohouse: 10,
        rent1house: 50,
        rent2house: 150,
        rent3house: 450,
        rent4house: 625,
        renthotel: 750,
        mortgage: 70,
        housecost: 100,
        hotelcost: 100,
    },
    {
        name: "States Avenue",
        color: PropertyType.Pink,
        price: 140,
        rentnohouse: 10,
        rent1house: 50,
        rent2house: 150,
        rent3house: 450,
        rent4house: 625,
        renthotel: 750,
        mortgage: 70,
        housecost: 100,
        hotelcost: 100,
    },
    {
        name: "Virginia Avenue",
        color: PropertyType.Pink,
        price: 160,
        rentnohouse: 12,
        rent1house: 60,
        rent2house: 180,
        rent3house: 500,
        rent4house: 700,
        renthotel: 900,
        mortgage: 80,
        housecost: 100,
        hotelcost: 100,
    },
];

export const orangeProperties: [PropertyInterface, PropertyInterface, PropertyInterface] = [
    {
        name: "St. James Place",
        color: PropertyType.Orange,
        price: 180,
        rentnohouse: 14,
        rent1house: 70,
        rent2house: 200,
        rent3house: 550,
        rent4house: 750,
        renthotel: 950,
        mortgage: 90,
        housecost: 100,
        hotelcost: 100,
    },
    {
        name: "Tennessee Avenue",
        color: PropertyType.Orange,
        price: 180,
        rentnohouse: 14,
        rent1house: 70,
        rent2house: 200,
        rent3house: 550,
        rent4house: 750,
        renthotel: 950,
        mortgage: 90,
        housecost: 100,
        hotelcost: 100,
    },
    {
        name: "New York Avenue",
        color: PropertyType.Orange,
        price: 200,
        rentnohouse: 16,
        rent1house: 80,
        rent2house: 220,
        rent3house: 600,
        rent4house: 800,
        renthotel: 1000,
        mortgage: 100,
        housecost: 100,
        hotelcost: 100,
    }
];